OHS-Hosting-Infrastructure/infrastructure

docs/user-research/README.md
docs/user-research/discussion-guide-template.md
docs/user-research/research-plan-phase1.md
docs/user-research/research-protocol.md

- Adds the start of research documentation and templates

Starts research documentation

---

docs/runbooks/vpn-access-requests.md

updates VPN access instructions

---

docs/how-we-work/vpn-access-list.md

-  Add Max Handelsman to VPN list

add max handelsman to vpn list

---

docs/how-we-work/deploy-eclkc.md

- Add a deployment document for the ECLKC HSICC team.

Rek 268 ecklc deploy

---

docs/runbooks/how-to-create-an-eclkc-login.md

- Update login URL for ECLKC dev from old and broken to new and working

Update ECLKC Dev login URL

---

docs/how-we-work/automated-actions.md

- Add initial list of automated tasks brainstorms

Add list of desired automation tasks

---

docs/research/applications/cc-cloudgov.md
docs/research/applications/eclkc-cloudgov.md

- Adds docs describing the truials and tribulation of cloud.gov for cc with as few typos as possible!
I tried to represent folks' participation -- plzlmk if I left anytgihg out! @reid-truss @avanti-joshi

adds cc cloud.gov doc

---

docs/how-we-work/definition-of-ready-done.md

- update definition of ready to include automation evaluation
- update definition of done to include automation (if applicable)

update def of ready and done

---

docs/adr/0011-jenkins-vpn-setup.md
docs/design-docs/moving-jenkins-behind-vpn.md

- Add initial writeup of plan to move Jenkins behind VPN

OHSH-354 add initial writeup of plan to move jenkins behind vpn

---

docs/adr/0011-jenkins-vpn-setup.md
docs/adr/0011-on-migration-to-cloud.gov.md
docs/adr/0012-on-migration-to-cloud.gov.md

- Add first draft of proposed ADR : "On whether to migrate hosted OHS apps to cloud.gov or not"
- Ignore markdownlint "ul-style" rule since it was fighting with markdownlint-toc hook
I left `?`s where I feel there may be gaps others could fill in.

Add ADR  on cloud.gov

---

docs/runbooks/maintenance.md

adds updating failures instrcutions

---

docs/research/polkit-vulnerability.md
docs/runbooks/how-to-run-ansible-commands.md

- Add writeup of research on polkit vulnerability

add Polkit vulnerability research document

---

docs/design-docs/moving-jenkins-behind-vpn.md

- Add more detail around outside services having access to Jenkins

modify jenkins design doc

---

docs/adr/template.md

Fix ADR template URL

---

.github/workflows/pre_commit.yaml
README.md

- Add github action to check pre-commit hooks, to block PRs that fail.
🔒 [Slack thread](https://trussworks.slack.com/archives/CLNC1MUBS/p1645737399108309)

Add github action for pre-commit checks

---

docs/runbooks/how-to-manage-qualys.md

- Add instructions for archiving Qualys scan reports.
- Tweak organization of ordered list steps to improve readability.

Add instructions for archiving qualys reports

---

docs/adr/0015-private-cert-management.md

Research around the options for going forward with managing private certificates.

ADR for private cert management - OHSH-511

---

docs/adr/0013-compare-vpn-edition.md

- comparing the free version of openVPN with the paid version and AWS VPN

ADR to compare different VPNs

---

docs/runbooks/how-to-manage-qualys.md

This PR adds more documentation around managing scan results from Qualys, including how to more easily manage results and generate Jira tickets.
- improved documentation for Qualys scans management

OHSH-536 Adding new documentation for Qualys scan triage

---

docs/runbooks/how-to-support-eclkc-drupal-deploy.md

To stop folks getting paged when you're doing a deploy.

Update drupal deploy for pagerduty override

---

docs/runbooks/debugging-outages.md

Wrap up OHSH-585 [Communicate DDOS Incident to AWS team](https://ocio-jira.acf.hhs.gov/browse/OHSH-585)
Last push to include everything we've learned from hunting down the DDOS incident of 4/17.
Includes more information about how to pick apart logs and what to do with them.

adds more info about debugging ddos

---

docs/how-we-work/private-ca.md

[OHSH-549](https://ocio-jira.acf.hhs.gov/browse/OHSH-549)
- add instructions for how to trust root cas in Firefox

OHSH-549 add private ca docs about firefox

---

docs/adr/0017-use-poetry-for-python-env-management.md

- Add ADR 0017: Use poetry for python venv management

Add ADR for "Use poetry for python venv management"
